import React, { useState, useEffect } from 'react';
import { AlertTriangle, ShieldCheck, CheckCircle2, ChevronDown, ChevronUp, FileText, ArrowRight, X } from 'lucide-react';
import { AlertItem, STRATIGRAPHIC_FORMATIONS } from '../data/wellsData.ts';
import { fetchAlerts, acknowledgeAlert, AlertsApiError } from '../services/alertsApi.ts';

interface CorrelationCenterPanelProps {
  currentDepthM?: number;
  onSelectAlert?: (alert: AlertItem) => void;
  onOpenReport?: (reportId: string) => void;
  onExportPdf?: () => void;
  // Optional well context (Well Intelligence integration, same pattern as
  // ReportBrowserTable): when set, alerts are loaded for that well only.
  activeWellId?: string;
  activeWellName?: string;
  onClearWellFilter?: () => void;
}

const SOURCE_TYPE_LABELS: Record<string, string> = {
  public_document: 'Real Oil India Document',
  government_data: 'Government Dataset',
  geospatial_data: 'Geospatial Dataset',
  derived: 'Derived Record',
  synthetic_demo: 'Synthetic Demo Data',
};

export const CorrelationCenterPanel: React.FC<CorrelationCenterPanelProps> = ({
  currentDepthM = 3500,
  onSelectAlert,
  onOpenReport,
  onExportPdf,
  activeWellId,
  activeWellName,
  onClearWellFilter,
}) => {
  // Alerts now come from the backend (GET /api/alerts, generated by the
  // Risk Intelligence engine) instead of the wellsData.ts fixture.
  const [alerts, setAlerts] = useState<AlertItem[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [expandedAlertId, setExpandedAlertId] = useState<string | null>(null);

  useEffect(() => {
    setIsLoading(true);
    setLoadError(null);
    fetchAlerts(activeWellId)
      .then((data) => setAlerts(data))
      .catch((err) => setLoadError(err instanceof AlertsApiError ? err.message : 'Could not reach the backend to load alerts.'))
      .finally(() => setIsLoading(false));
  }, [activeWellId]);

  const toggleExpand = (id: string) => {
    setExpandedAlertId(expandedAlertId === id ? null : id);
  };

  const handleAcknowledge = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      const updated = await acknowledgeAlert(id);
      setAlerts((prev) => prev.map((a) => (a.id === id ? updated : a)));
    } catch (err) {
      setLoadError(err instanceof AlertsApiError ? err.message : 'Could not reach the backend to acknowledge this alert.');
    }
  };

  return (
    <div className="rounded-lg border-2 border-[#5c4f42] bg-[#f5ede1] shadow-md overflow-hidden flex flex-col h-full">
      {/* Dark Header Strip matching screenshot */}
      <div className="bg-[#463d35] text-white px-3.5 py-2 flex items-center justify-between border-b border-[#352d26]">
        <div className="flex items-center gap-2">
          <h2 className="text-sm font-bold tracking-wide font-['Chakra_Petch',sans-serif]">
            Cross-Well Correlation & Operations
          </h2>
        </div>
        
        <div className="flex items-center gap-2">
          {onExportPdf && (
            <button
              type="button"
              onClick={onExportPdf}
              className="px-2 py-0.5 rounded bg-amber-500 hover:bg-amber-400 text-stone-950 font-mono text-[10px] font-bold flex items-center gap-1 transition-colors cursor-pointer shadow-xs"
              title="Export Current Well Drilling Summary Report (PDF)"
            >
              <FileText className="w-3 h-3" />
              <span>Export PDF</span>
            </button>
          )}
          <span className="text-[11px] font-mono text-amber-300 hidden sm:inline">
            Real-time Engine
          </span>
        </div>
      </div>

      {/* Center Layout: 3 Columns (Active Well Tube, Formation Lithology, Predictive Alerts) */}
      <div className="p-3 bg-[#f5ede1] flex-1 grid grid-cols-12 gap-2 select-none overflow-y-auto">
        
        {/* Sub-Column 1: Active Well Depth Tube Gauge */}
        <div className="col-span-2 sm:col-span-2 flex flex-col items-center border-r border-[#d4c4b0] pr-1">
          <div className="text-xs font-bold text-[#2d251d] text-center mb-1 font-['Chakra_Petch',sans-serif]">
            Active Well
          </div>

          {/* Vertical Borehole Gauge */}
          <div className="relative w-12 flex-1 min-h-[500px] flex items-center justify-center">
            {/* Left Depth Labels matching screenshot: 0, 2500m, 3500m, 4500m, 5500m */}
            <div className="absolute -left-6 top-0 bottom-0 flex flex-col justify-between text-[10px] font-mono text-[#5c4f42] font-semibold text-right w-10">
              <span className="leading-none">0</span>
              <span className="leading-none">2500m -</span>
              <span className="leading-none font-bold text-[#b91c1c]">3500m -</span>
              <span className="leading-none">4500m -</span>
              <span className="leading-none">5500m -</span>
            </div>

            {/* Borehole outer casing tube */}
            <div className="w-8 h-full rounded-b-full border-2 border-[#3d3227] bg-[#a89985]/40 relative overflow-hidden shadow-inner ml-3">
              {/* Drilled borehole fluid column */}
              <div 
                className="w-full bg-[#8c7862]/60 absolute top-0 transition-all duration-300"
                style={{ height: '64%' }}
              />

              {/* Drill pipe string running down */}
              <div className="absolute top-0 left-1/2 -translate-x-1/2 w-1.5 h-[64%] bg-[#241d17]">
                {/* Tool joints */}
                <div className="w-2.5 h-1 bg-[#473b30] -ml-0.5 absolute top-[20%]" />
                <div className="w-2.5 h-1 bg-[#473b30] -ml-0.5 absolute top-[40%]" />
                <div className="w-2.5 h-1 bg-[#473b30] -ml-0.5 absolute top-[60%]" />
                <div className="w-2.5 h-1 bg-[#473b30] -ml-0.5 absolute top-[80%]" />
              </div>

              {/* Drill bit at 3,500m depth with red indicator */}
              <div 
                className="absolute left-1/2 -translate-x-1/2 w-4 h-3 bg-[#dc2626] border border-black rounded-b-sm shadow-xs transition-all duration-300 animate-pulse"
                style={{ top: '63%' }}
                title="Current Bit Depth: 3,500m (Barail Formation)"
              />
            </div>
          </div>
        </div>

        {/* Sub-Column 2: Formation Map Stratigraphic Column */}
        <div className="col-span-3 sm:col-span-3 flex flex-col items-center border-r border-[#d4c4b0] pr-1">
          <div className="text-xs font-bold text-[#2d251d] text-center mb-1 font-['Chakra_Petch',sans-serif]">
            Formation Map
          </div>

          {/* Stratigraphic Column with Lateral Flare Hazard Zone */}
          <div className="w-full flex-1 min-h-[500px] relative rounded-md border border-[#3d3227] overflow-hidden shadow-inner flex flex-col">
            {/* 1. Alluvium / Dhekiajuli (0 - 800m) */}
            <div className="h-[12%] bg-[#d4a373] border-b border-[#3d3227]/40 flex items-center justify-center text-[9px] font-mono text-[#2c241c] px-1 text-center">
              Alluvium
            </div>

            {/* 2. Girujan Clay (800 - 2100m) */}
            <div className="h-[22%] bg-[#9381ff]/50 border-b border-[#3d3227]/40 flex items-center justify-center text-[9px] font-mono text-[#2c241c] px-1 text-center">
              Girujan Clay
            </div>

            {/* 3. Tipam Sandstone (2100 - 3050m) */}
            <div className="h-[16%] bg-[#f4a261] border-b border-[#3d3227]/40 flex items-center justify-center text-[9px] font-mono text-[#2c241c] px-1 text-center">
              Tipam Sand
            </div>

            {/* 4. Surma Group (3050 - 3350m) */}
            <div className="h-[8%] bg-[#e76f51] border-b border-[#3d3227]/40 flex items-center justify-center text-[9px] font-mono text-white px-1 text-center">
              Surma
            </div>

            {/* 5. Barail High Hazard Flare (3350 - 4200m) matching the exact screenshot visual! */}
            <div className="h-[24%] relative overflow-hidden bg-[#eab308] border-y-2 border-[#b91c1c] flex items-center justify-center">
              {/* Lateral yellow-to-red flared shape */}
              <div 
                className="absolute inset-0 bg-gradient-to-r from-[#eab308] via-[#f97316] to-[#ef4444] opacity-90"
                style={{
                  clipPath: 'polygon(0% 15%, 100% 30%, 100% 85%, 0% 70%)',
                }}
              />
              <div className="relative z-10 text-center font-mono font-bold text-[9px] text-[#450a0a] bg-white/70 px-1 py-0.5 rounded shadow-xs">
                ⚠️ HIGH LOSS / KICK ZONE
                <div className="text-[8px] text-[#7f1d1d]">3350m - 4200m</div>
              </div>
            </div>

            {/* 6. Kopili Shale (4200 - 4800m) */}
            <div className="h-[10%] bg-[#457b9d] border-b border-[#3d3227]/40 flex items-center justify-center text-[9px] font-mono text-white px-1 text-center">
              Kopili Shale
            </div>

            {/* 7. Sylhet Limestone & Basement (>4800m) */}
            <div className="h-[8%] bg-[#5c4f42] flex items-center justify-center text-[9px] font-mono text-[#dfd4c3] px-1 text-center">
              Sylhet & Base
            </div>
          </div>
        </div>

        {/* Sub-Column 3: Real-Time Predictive Alerts & Recommendations */}
        <div className="col-span-7 sm:col-span-7 flex flex-col">
          <div className="text-xs font-bold text-[#2d251d] mb-1 font-['Chakra_Petch',sans-serif] flex items-center justify-between gap-2 flex-wrap">
            <span>Real-time Predictive Alerts & Recommendations</span>
            <span className="text-[10px] font-mono bg-red-100 text-red-700 px-1.5 py-0.2 rounded border border-red-300 font-bold">
              {alerts.length} Active
            </span>
          </div>

          {activeWellId && (
            <div className="mb-1.5 flex items-center gap-1.5 bg-[#463d35] text-amber-200 text-[10px] font-mono px-2 py-1 rounded w-fit">
              <span>Filtered to: <strong>{activeWellName || activeWellId}</strong></span>
              {onClearWellFilter && (
                <button type="button" onClick={onClearWellFilter} className="hover:text-white cursor-pointer" title="Clear well filter">
                  <X className="w-3 h-3" />
                </button>
              )}
            </div>
          )}

          {isLoading && (
            <div className="p-2 mb-1.5 bg-[#ebdcc8] border border-[#c4b5a2] text-[#5c5247] rounded text-[10px] font-mono text-center">
              Loading alerts from backend…
            </div>
          )}
          {!isLoading && loadError && (
            <div className="p-2 mb-1.5 bg-red-50 border border-red-300 text-red-800 rounded text-[10px] font-mono text-center">
              {loadError}
            </div>
          )}
          {!isLoading && !loadError && alerts.length === 0 && (
            <div className="p-2 mb-1.5 bg-emerald-50 border border-emerald-300 text-emerald-800 rounded text-[10px] font-mono text-center">
              No active alerts — no configured risk signal currently detected.
            </div>
          )}

          {/* Stack of Alert Cards matching the screenshot */}
          <div className="space-y-2 overflow-y-auto max-h-[510px] pr-1">
            {alerts.map((alert) => {
              const isExpanded = expandedAlertId === alert.id;
              const isAcknowledged = alert.acknowledged;

              return (
                <div
                  key={alert.id}
                  onClick={() => {
                    toggleExpand(alert.id);
                    onSelectAlert?.(alert);
                  }}
                  className={`p-2.5 rounded-md border transition-all cursor-pointer shadow-xs ${
                    alert.severity === 'CRITICAL'
                      ? 'bg-[#fee2e2] border-[#f87171] hover:bg-[#fecaca]'
                      : 'bg-[#fef3c7] border-[#fde047] hover:bg-[#fde68a]'
                  } ${isAcknowledged ? 'opacity-60 bg-gray-100 border-gray-300' : ''}`}
                >
                  <div className="flex items-start gap-2">
                    {/* Warning Triangle Icon */}
                    <div className="mt-0.5 text-amber-600 shrink-0">
                      <AlertTriangle className="w-4 h-4 fill-amber-500 text-black" />
                    </div>

                    {/* Alert Text & Recommendation matching screenshot wording */}
                    <div className="flex-1 min-w-0">
                      <div className="text-xs font-bold text-[#1c1815] leading-snug flex items-center gap-1.5 flex-wrap">
                        <span>{alert.title}</span>
                        {alert.isSimulation && (
                          <span
                            className="bg-amber-200 text-amber-900 border border-amber-400 text-[8px] font-mono px-1 py-0.2 rounded font-bold uppercase"
                            title="Includes a signal derived from simulated demo telemetry — not proprietary Oil India eRTMAC data"
                          >
                            Simulated
                          </span>
                        )}
                      </div>
                      <div className="text-[11px] text-[#374151] mt-0.5">
                        <strong className="text-[#1c1815]">Recommendation:</strong> {alert.recommendation}
                      </div>

                      {/* Expandable Evidence Details */}
                      {isExpanded && (
                        <div className="mt-2 pt-2 border-t border-black/10 text-[11px] text-[#1f2937] space-y-1.5 font-sans">
                          <div className="bg-white/70 p-2 rounded border border-black/10">
                            <span className="font-semibold text-[#111827]">Risk Signal Detail:</span>{' '}
                            {alert.message}
                          </div>

                          <div className="text-[10px] font-mono text-[#4b5563]">
                            <strong>Well:</strong> {alert.wellRef} • Depth: {alert.depthM}m
                          </div>

                          {alert.evidence && alert.evidence.length > 0 && (
                            <div className="flex flex-wrap gap-1">
                              {alert.evidence.map((ev, evIdx) => (
                                <span
                                  key={evIdx}
                                  className={`text-[9px] font-mono px-1.5 py-0.2 rounded border ${
                                    ev.sourceType === 'synthetic_demo'
                                      ? 'bg-amber-100 text-amber-900 border-amber-400'
                                      : 'bg-emerald-100 text-emerald-900 border-emerald-400'
                                  }`}
                                >
                                  {SOURCE_TYPE_LABELS[ev.sourceType] || ev.sourceType}
                                </span>
                              ))}
                            </div>
                          )}

                          <div className="mt-1.5 flex items-center justify-between gap-2 pt-1">
                            <button
                              onClick={(e) => handleAcknowledge(alert.id, e)}
                              className={`px-2 py-0.5 text-[10px] rounded font-semibold transition-colors flex items-center gap-1 ${
                                alert.acknowledged
                                  ? 'bg-emerald-700 text-white'
                                  : 'bg-black text-white hover:bg-gray-800'
                              }`}
                            >
                              <CheckCircle2 className="w-3 h-3" />
                              {alert.acknowledged ? 'Acknowledged' : 'Acknowledge Alert'}
                            </button>

                            {alert.evidence?.some((ev) => ev.type === 'historical_event' && ev.eventId) && (
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  const eventEvidence = alert.evidence!.find((ev) => ev.type === 'historical_event' && ev.eventId);
                                  if (eventEvidence?.eventId) onOpenReport?.(eventEvidence.eventId);
                                }}
                                className="px-2 py-0.5 text-[10px] rounded bg-amber-700 hover:bg-amber-800 text-white font-semibold transition-colors flex items-center gap-1"
                              >
                                <FileText className="w-3 h-3" />
                                <span>View Evidence</span>
                              </button>
                            )}
                          </div>
                        </div>
                      )}
                    </div>

                    {/* Chevron toggle icon */}
                    <div className="text-[#6b7280]">
                      {isExpanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

      </div>
    </div>
  );
};
